server:
  port: 8081

spring:
  #springboot2.6以上兼容swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #数据库连接
  datasource:
    #mysql5.x的驱动
    driver-class-name: com.mysql.jdbc.Driver
    #mysql8.x的驱动
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqupt?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password:

  #格式化时间返回给前端需要加jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

